### ISSUE TITLE
6.5 Boxplot

### ISSUE THREAD

**Issue by dedouch** [MarekProkop/excel-r#3]
Poslední věta:
Nejvyšší droid je ale podobně vysoký jako nejvyšší člověk (konec horního fousu).

Nemělo by být:
Nejvyšší droid (konec horního fousu) je ale podobně vysoký jako nejnižší člověk (konec dolního fousu).

**Comment by MarekProkop** [comment]
Bavíme se o tohle obrázku?

![image](https://user-images.githubusercontent.com/52025262/159943532-7f107a1a-1318-481f-9de1-02ea9e80fbce.png)

Na něm jsou horní fousy obou grafů v přibližně stejné výšce, čili obě skupiny mají přibližně stejně vysoké své nejvyšší zástupce.
