### ISSUE TITLE
Výstup do xlsx

### ISSUE THREAD

**Issue by Lurcherida** [MarekProkop/excel-r#5]
Dobrý den, 

stále dokola zkouším Vaše návody a vytvářím si svou klíčovku ... Jádro pudla jsem asi už nějak pochopila (jak na odmazávání nerelevantních výrazů, také jak vytvářet kategorie), co mi není jasné je jakým způsobem udělat výstup do excelové tabulky. 
Zkoušela jsem writexl, ten mi ale pokaždé při načtení knihovny shodí celé RStudio. Tak jsem si ho vyzkoušela na Cloudu a tam mi to funguje, jen nevím jakým způsobem (a cestou) vytáhnout data z kwr do excelu... 
Děkuji za pomoc
Katka

**Comment by MarekProkop** [comment]
Dobrý den,

pokud již máte alespoň částečně hotovou klasifikaci v objektu `kwr`, pak zapíšete klasifikované dotazy do Excelu ve složce `data` (musí už existovat) např. takto:

```
library(writexl)
kwr |> 
  kwr_classified_queries() |> 
  write_xlsx(path = "data/classified_queries.xlsx")
```

Tento kód jsem teď zkoušel a funguje dobře.

Že vám načtení balíčku _writexl_ havaruje, je divné. Je to dost populární a široce používaný balíček. Asi by bylo vhodné to nahlásit autorovi na https://github.com/ropensci/writexl.

**Comment by Lurcherida** [comment]
Dobrý den, 

děkuji moc za odpovědi. 
Vyřešily všechny mé problémy ;)
WriteXl mi funguje dobře, problém byl v podobném balíčku WriteXlsx - ten mi padal
